### ISSUE TITLE
gmake vs make ✨🤕

### ISSUE THREAD

**Issue by hrefhref** [elixir-lang/elixir_make#38]
So #37 made me think. The majority of Elixir projects will write `Makefile` for GNU make, so developers expects that `elixir_make` will always use it.

That PR added netbsd, but there's also solaris, smartos, dragonfly, …. How can we find a way to ensure we'll use gmake consistently ?

Could we just call `gmake` if `:os.type()` isn't `{:unix, :linux}` ? I can't really think of any other unices that bundles gnu make as a default.

**Comment by Kleidukos** [comment]
In practice, except if you're running HURD, every non-linux UNIX runs their own flavour of non-GNU make.

**Comment by whatyouhide** [comment]
Has this caused actual problems that we are aware of? I want to make sure we're not spending time designing a super generic solution when no one actually ran into anything bad related to this, you know 😄

**Comment by Kleidukos** [comment]
Hi @whatyouhide! Issues were raised while testing a software called Pleroma written in Elixir, on different Unices.
The goal is *not* to spend time designing a super generic solution, but to actively promote the use of the `gmake` executable by default on all non-Linux Unices. A generic solution would account for every flavours of Make in the Unix world. The solution that is proposed is to *specialise* rather than *generalise*.

**Comment by whatyouhide** [comment]
I'm not super familiar with all the Make stuff (😅) so I'm good with making `gmake` default on all non-Linux Unix systems. Could you send a PR @Kleidukos? :)

**Comment by josevalim** [comment]
A PR for using gmake in other Unices is welcome if you still believe ti is a useful change. Closing this for now!
