### ISSUE TITLE
[Proposal] Add a feature to call configure before building

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir_make#42]
Hi,

I propose add a feature to call `configure` before building, in order to enable NIFs to be configurable by Autoconf.

I have a plan to apply it to Pelemay.

**Comment by josevalim** [comment]
Hi @zacky1972, you can achieve this in a couple ways:

1. Have the makefile itself call `configure`

2. alias the compile command to call configure for you. In your mix.exs, you can do:

    aliases: [compile: [&configure/1, "compile"]]

And then:

    defp configure(_args) do
      System.cmd("configure", [...])
    end

Because of that, this is not something I believe we need to support directly in elixir_make. Thanks!

**Comment by zacky1972** [comment]
Thank you!
