### ISSUE TITLE
Failed to load NIF when load NIFs on priv in Application.app_dir after iex -S mix, cleaning, building and installing into Application.app_dir by elixir_make

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir_make#45]
Hi,

Sample code is here:
https://github.com/zacky1972/elixir_make_test

When running `iex -S mix` on the project, the error "Failed to load NIF" occurs.

Redefining the module `ElixirMakeTest` will eliminate this error. Removing `"clean"` of `:compile` of `:aliases` in `project` of `mix.exs` will also eliminate this error.

I feel it may be some kind of bugs, or it requires some workaround.

I've tested it on Elixir 1.11.2, Erlang 23.1.5 and elixir_make 0.6.2.

**Comment by josevalim** [comment]
@zacky1972 the issue in your code is because you have this:

```
aliases: [
  compile: ["clean", "compile", &install/1]
],
```

What is happening is that you are copying the `.so` file (in `install/1`) after the Elixir code is compiled. You need to make it so the task called by elixir_make is the one that installs the `.so`. In other words, you need to guarantee that before Elixir compiles the code, that the .so file is already in the correct place. Thanks!

**Comment by zacky1972** [comment]
Thank you! I fixed this issue of my project.
